spring.application.name=media-service
server.port=8087

spring.datasource.url=jdbc:mysql://localhost:3306/cs_media_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=Soul@3107
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=ConnectSphere_JWT_Secret_Key_Change_In_Prod_2026!

app.services.auth-service.url=http://localhost:8081

# Local media storage
app.media.upload-dir=uploads/media

# File upload limits
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Story expiry scheduler (every 5 min)
app.scheduler.story-expiry-cron=0 */5 * * * *

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
app.rabbitmq.exchange=connectsphere.exchange
app.rabbitmq.routing-key.story-expired=story.expired

management.endpoints.web.exposure.include=health,info
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
